[site]
title = "Xin Guo"
description = "Personal website of Xin Guo."
favicon = "/favicon.svg"
last_updated = "July 28, 2026"

[author]
name = "Xin Guo"
title = "PhD Student"
institution = """Institute of Geodesy
Graz University of Technology
(Technische Universität Graz)"""
avatar = "/profile-xin.jpg"

[social]
# Contact information. Remove any field you do not want to display publicly.
email = "xin.guo@student.tugraz.at"
location = "Graz, Austria"
location_url = "https://www.google.com/maps/place/Graz+University+Of+Technology/@47.0641765,15.4527816,185m/data=!3m1!1e3!4m6!3m5!1s0x476e4a85d3955555:0x192b0deae0c79ec4!8m2!3d47.0642547!4d15.4529602!16s%2Fg%2F11hzsvs4ps?entry=ttu&g_ep=EgoyMDI2MDcyMi4wIKXMDSoASAFQAw%3D%3D"
location_details = [
  "ST 01 122, Steyrergasse 30,",
  "8010, Graz, Austria"
]
orcid = "https://orcid.org/0000-0002-8748-6036"
github = "https://github.com/GuoXin-Ink"
linkedin = "https://www.linkedin.com/in/xin-guo-04334b330/"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = true
locales = ["zh", "en"]
default_locale = "en"
# "auto" means the locale will be determined by the browser's language setting, "fixed" means the locale will be fixed to the default locale (but can be switched still, if you want to disable, set "enable=false")
mode = "fixed"
fixed_locale = "en"
# If true, PRISM will remember user's language preference in browser's localStorage
persist = true
# Show a language switcher on the top right corner
switcher = true

[i18n.labels]
zh = "中文"
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "News"
type = "page"
target = "news"
href = "/news"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Teaching"
type = "page"
target = "teaching"
href = "/teaching"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "Services"
type = "page"
target = "services"
href = "/services"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
